FROM debian:bullseye

COPY app /code/app
COPY libs /code/libs

# hadolint ignore=DL3008,DL3015,DL4006
RUN apt-get update && apt-get install -y bash curl && curl -1sLf \
    'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash \
    && apt-get update && apt-get install -y infisical && \
    rm -rf /var/lib/apt/lists/*

ENV INFISICAL_TOKEN="" ENV="dev"

ENTRYPOINT ["infisical", "run", "--command", "/bin/bash /code/app"]
