services:

  app:
    image: meetup-infisical:0.1.0
    tty: true
    stdin_open: true
    environment:
      ENV: ${ENV:-saispas}
      SECRET: ${SECRET:-saispas}
      PUBLIC_KEY: ${PUBLIC_KEY:-saispas}
      PRIVATE_KEY: ${PRIVATE_KEY:-saispas}
